"use client";
import React, { useEffect, useState } from "react";
import {
	Sheet,
	SheetClose,
	SheetContent,
	SheetTitle,
	SheetTrigger,
} from "../../ui/sheet";
import { Button } from "../../ui/button";
import { useTranslations } from "next-intl";
import { z } from "zod";
import AutoForm from "../../ui/auto-form";
import {
	addDoc,
	collection,
	doc,
	query,
	serverTimestamp,
	setDoc,
	where,
	type DocumentData,
	type DocumentReference,
	type Timestamp,
} from "firebase/firestore";
import { useCollectionOnce, useDocument } from "react-firebase-hooks/firestore";
import { useUploadFile } from "react-firebase-hooks/storage";
import { db, storage } from "@/firebase/firebase";
import useCompanyId from "@/hooks/useCompanyId";

import SelectMenu from "./select-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { InputWithIcon } from "@/components/ui/input-with-icon";
import { EuroIcon } from "lucide-react";
import { IconMeterCube } from "@tabler/icons-react";
import type { Order } from "@/models/orders";
import { useToast } from "@/components/ui/use-toast";
import { getDownloadURL, ref, uploadBytesResumable } from "firebase/storage";
import type { FirebaseError } from "firebase/app";

// All of the comments are selected menus or autoGenerated

export default function AddOrdersSheet() {
	const t = useTranslations("AddOrderSheet");
	const companyId = useCompanyId();

	const [drivers, driverLoading, driverError] = useCollectionOnce(
		query(
			collection(db, "users"),
			where("companyId", "==", companyId),
			where("type", "==", "driver"),
		),
	);
	const [companies, companiesLoading, companiesError] = useCollectionOnce(
		query(collection(db, "companies")),
	);
	const [trucks, truckLoading, truckError] = useCollectionOnce(
		query(collection(db, "trucks"), where("companyId", "==", companyId)),
	);

	const [orders] = useCollectionOnce(
		query(collection(db, "orders"), where("companyId", "==", companyId)),
	);

	if (driverError || companiesError || truckError) {
		console.error(driverError, companiesError, truckError);
	}

	const sheetFormSchema = z.object({
		status: z
			.enum(["Picking Up", "In Delivery", "Delivered"])
			.default("Picking Up")
			.describe(""),
		driver: z.custom((data) => {
			// if (data === null || data === undefined) return false;

			return true;
		}),
		truck: z.custom((data) => {
			// if (data === null || data === undefined) return false;

			return true;
		}),
		company: z.object({
			name: z.string().min(1),
			worker: z.string().min(1),
		}),
		palletes: z
			.array(
				z.object({
					width: z.coerce.number().default(1),
					length: z.coerce.number().default(1),
					height: z.coerce.number().default(1),
					weight: z.coerce.number().default(1),
				}),
			)
			.nonempty("Palletes must have at least one item")
			.default([
				{
					width: 1,
					length: 1,
					height: 1,
					weight: 1,
				},
			]),
		pickUps: z
			.array(
				z.object({
					address: z.string(),
					start: z.coerce.date(),
					end: z.coerce.date(),
				}),
			)
			.nonempty("Pickups must have at least one item")
			.default([
				{
					address: "",
					start: new Date(),
					end: new Date(),
				},
			]),
		deliveries: z
			.array(
				z.object({
					address: z.string(),
					start: z.coerce.date(),
					end: z.coerce.date(),
				}),
			)
			.nonempty("Deliveries must have at least one item")
			.default([
				{
					address: "",
					start: new Date(),
					end: new Date(),
				},
			]),
		documents: z.instanceof(File).optional(),
		note: z.string().optional(),
		// createdAt: z.custom<Timestamp>((data) => {
		//   return serverTimestamp();
		// }), // Replace with actual Timestamp schema
	});

	const [driverName, setDriverName] = React.useState("");
	const [driverRef, setDriverRef] = useState<DocumentReference | null>(null);

	const [licensePlate, setTruckPlate] = React.useState("");
	const [truckRef, setTruckRef] = useState<DocumentReference | null>(null);

	const [companyName, setCompanyName] = React.useState("");
	const [companyRef, setCompanyRef] = useState<DocumentReference | null>(null);

	const { toast } = useToast();
	const [uploadFile, uploading, snapshot, error] = useUploadFile();

	function addOrder(values: Order | null) {
		if (!values || !companyId || !companyRef || !driverRef || !truckRef) {
			console.error("Values are null");
			toast({
				title: "Error",
				description: "Values are null",
				variant: "destructive",
			});
			return;
		}

		if (
			values.status === undefined ||
			values.driver === undefined ||
			values.truck === undefined ||
			values.company === undefined ||
			values.company.name === undefined ||
			values.company.worker === undefined ||
			values.palletes === undefined ||
			values.pickUps === undefined ||
			values.deliveries === undefined ||
			values.documents === undefined
		) {
			console.error("Values are undefined", values);
			toast({
				title: "Error",
				description: "Values are undefined",
				variant: "destructive",
			});
			return;
		}

		if (values.documents === null || values.documents === undefined) {
			console.error("Documents are null");
			toast({
				title: "Error",
				description: "Documents are null",
				variant: "destructive",
			});
			return;
		}

		console.log("addOrder", values);
		const currentDate = new Date();

		const numbers = licensePlate.match(/\d+/g)?.join("") ?? "";
		const id = `${currentDate.getFullYear()}${currentDate.getMonth()}${currentDate.getDate()}${numbers}${orders?.docs.length}`;

		// upload documents to firebase storage

		const document = values.documents as File;

		const fileRef = ref(storage, `orders/${companyId}/${id}/${document.name}`);

		uploadFile(fileRef, document, {
			contentType: document.type,
		})
			.catch((e: FirebaseError) => console.error(e.message))
			.then(() => {
				getDownloadURL(fileRef).then((downloadUrl) => {
					values.documents = {
						name: document.name,
						url: downloadUrl,
					};

					setDoc(doc(db, `/orders/${id}`), {
						...values,
					});

					toast({
						title: "Success",
						description: "Order added successfully",
						variant: "success",
					});

					setOpen(false);
				});
			});
	}

	const [values, setValues] = useState<Order | null>(null);

	const [open, setOpen] = useState(false);

	return (
		<Sheet open={open} onOpenChange={setOpen}>
			<SheetTrigger>
				<Button>{t("title")}</Button>
			</SheetTrigger>
			<SheetContent className="overflow-y-scroll ">
				{!driverLoading && !companiesLoading && (
					<>
						<SheetTitle className="w-full py-6">{t("title")}</SheetTitle>
						<AutoForm
							formSchema={sheetFormSchema}
							onValuesChange={(values) => {
								console.log("documents", values.documents);

								if (!(driverRef && truckRef && companyRef)) {
									console.error("Driver, Truck or Company is not selected");
									return;
								}

								if (!values.documents) {
									console.error("Documents are not selected");
									return;
								}

								setValues({
									status: values.status ?? "Picking Up",
									driver: driverRef,
									truck: truckRef,
									companyId: companyId ?? "",
									company: {
										ref: companyRef,
										name: companyName,
										worker: values.company?.worker ?? "",
									},
									palletes: values.palletes as {
										width: number;
										length: number;
										height: number;
										weight: number;
									}[],
									pickUps: values.pickUps as {
										address: string;
										start: Date;
										end: Date;
									}[],
									deliveries: values.deliveries as {
										address: string;
										start: Date;
										end: Date;
									}[],
									documents: values.documents,
									note: values.note ?? "",
								});
							}}
							className="w-full p-2 flex flex-col gap-6"
							fieldConfig={{
								documents: {
									fieldType: "file",
								},
								driver: {
									renderParent: ({ children }) => (
										<SelectMenu
											selectedValue={driverName}
											setValue={setDriverName}
											values={drivers}
											setRef={setDriverRef}
											selectText="Select Driver"
											filterText="Filter Drivers"
											addText="Add Driver"
											field="name"
										/>
									),
								},
								truck: {
									renderParent: ({ children }) => (
										<SelectMenu
											selectedValue={licensePlate}
											setValue={setTruckPlate}
											values={trucks}
											setRef={setTruckRef}
											selectText="Select Truck"
											filterText="Filter Trucks"
											addText="Add Truck"
											field="licensePlate"
										/>
									),
								},
								company: {
									name: {
										renderParent: ({ children }: any) => (
											<SelectMenu
												selectedValue={companyName}
												setValue={setCompanyName}
												values={companies}
												setRef={setCompanyRef}
												selectText="Select Company"
												filterText="Filter Companies"
												addText="Add Company"
												field="name"
											/>
										),
									},
								},
								palletes: {
									width: {
										renderParent: ({ children }: any) => (
											<div className="flex flex-col gap-2">
												<Label>Width</Label>
												<InputWithIcon
													inputMode="numeric"
													inputProps={{
														type: "number",
													}}
													position="trailing"
													icon={<h1>cm</h1>}
												/>
											</div>
										),
									},
									length: {
										renderParent: ({ children }: any) => (
											<div className="flex flex-col gap-2">
												<Label>Length</Label>
												<InputWithIcon
													inputMode="numeric"
													inputProps={{
														type: "number",
													}}
													position="trailing"
													icon={<h1>cm</h1>}
												/>
											</div>
										),
									},
									height: {
										renderParent: ({ children }: any) => (
											<div className="flex flex-col gap-2">
												<Label>Height</Label>
												<InputWithIcon
													inputMode="numeric"
													inputProps={{
														type: "number",
													}}
													position="trailing"
													icon={<h1>cm</h1>}
												/>
											</div>
										),
									},
									weight: {
										renderParent: ({ children }: any) => (
											<div className="flex flex-col gap-2">
												<Label>Weight</Label>
												<InputWithIcon
													inputMode="numeric"
													inputProps={{
														type: "number",
													}}
													position="trailing"
													icon={<h1>kg</h1>}
												/>
											</div>
										),
									},
								},
							}}
						>
							<div className="flex sticky bottom-0 justify-center items-center gap-4 ">
								<SheetClose>
									<Button
										type="button"
										className="min-w-32"
										variant={"outline"}
									>
										{t("cancel")}
									</Button>
								</SheetClose>
								<Button
									className="min-w-32"
									onClick={() => addOrder(values)}
									type="submit"
								>
									{t("submit")}
								</Button>
							</div>
						</AutoForm>
					</>
				)}
			</SheetContent>
		</Sheet>
	);
}
