import Favicon from "@/components/ui/favicon";
import { Toaster } from "@/components/ui/toaster";
import MotionConfigProvider from "@/context/motion-config-provider";
import { ThemeProvider } from "@/context/theme-provider";
import { locales } from "@/lib/i18n";
import { IconX } from "@tabler/icons-react";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { Noto_Sans } from "next/font/google";
import "../globals.css";

const noto = Noto_Sans({
	preload: true,
	weight: ["400", "500", "600", "700", "800", "900"],
	subsets: ["cyrillic", "latin"],
});

export function generateStaticParams() {
	return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
	title: {
		template: "%s | Truck Fleet",
		default: "Truck Fleet",
	},

	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	unstable_setRequestLocale(locale);
	const messages = await getMessages();

	return (
		<html lang={locale} suppressHydrationWarning>
			<head>
				<meta charSet="utf-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/packages_light.png" />
			</head>
			<body className={noto.className}>
				<div
					data-tauri-drag-region
					className="fixed top-0 z-[1000000] flex h-10 w-full bg-white justify-end "
				>
					<IconX className="h-10 w-10 text-black" />
					<IconX className="h-10 w-10 text-black" />
					<IconX className="h-10 w-10 text-black" />
				</div>

				<Favicon />
				<MotionConfigProvider
					props={{
						reducedMotion: "user",
					}}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<NextIntlClientProvider messages={messages}>
							<main>{children}</main>
							<Toaster />
						</NextIntlClientProvider>
					</ThemeProvider>
				</MotionConfigProvider>
			</body>
		</html>
	);
}
